language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - TESTER_PHP_BIN="php"
  - TESTER_PHP_BIN="php-cgi"
  - TESTER_PHP_BIN="hhvm"

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.3.3

  exclude:

    - php: 5.3.3
      env: TESTER_PHP_BIN="hhvm"

    - php: 5.4
      env: TESTER_PHP_BIN="hhvm"

    - php: 5.5
      env: TESTER_PHP_BIN="hhvm"

    - php: 5.6
      env: TESTER_PHP_BIN="hhvm"

    - php: 7.0
      env: TESTER_PHP_BIN="hhvm"

    - php: hhvm
      env: TESTER_PHP_BIN="php-cgi"
  include:
    - php: 5.5
      env: dependencies="--prefer-lowest --prefer-stable" PHP_BIN=php

services:
  - redis-server

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -s ./tests/
#  - ./vendor/bin/tester -p $TESTER_PHP_BIN -c ./tests/GalekTests/Socials/php.ini -s ./tests/

after_failure:
  # Vytiskne obsah souborů *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
  - if [ $TRAVIS_PHP_VERSION == "5.3.3" ]; then composer --global config disable-tls true; composer --global config secure-http false; fi
  - travis_retry composer update --no-interaction --prefer-dist $dependencies
  - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction

sudo: false


cache:
    directories:
        - $HOME/.composer/cache
